backend:
  name: git-gateway
  repo: alianza/nextjs-netlify-blog-template-test
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow
logo_url: https://pensive-mclean-91ddb5.netlify.app/images/logo.webp

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Number of Posts per page"
            name: "posts_per_page"
            widget: "number"
          - label: "Number of Events per page"
            name: "events_per_page"
            widget: "number"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - { label: "Slug", name: "slug", widget: "string", hint: "The part of a URL identifies the author" }
              - { label: "Name", name: "name", widget: "string", hint: "First and Last" }
              - { label: "Introduction", name: "introduction", widget: "text" }

      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - { label: "Slug", name: "slug", widget: "string", hint: "The part of a URL identifies the tag" }
              - { label: "Display Name", name: "name", widget: "string", hint: "Tag name for displaying on the site" }

      - name: "locations"
        label: "Locations"
        file: "meta/locations.yml"
        description: "Location description"
        fields:
          - name: locations
            label: Locations
            label_singular: "Location"
            widget: list
            fields:
              - { label: "Slug", name: "slug", widget: "string", hint: "The part of a URL identifies the location (lowercase!)" }
              - { label: "Name", name: "name", widget: "string", hint: "Name of location" }
              - { label: "Address", name: "address", widget: "string", hint: "Full address" }
              - { label: "Location", name: "location", widget: "map", hint: "Location on map" }
              - { label: "Featured Image", name: "thumbnail", widget: "image", choose_url: true }
              - { label: "Description", name: "description", widget: "text", }

  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        search_fields:
          - "authors.*.name"
        display_fields:
          - "authors.*.name"
        value_field: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          search_fields:
            - "tags.*.name"
          display_fields:
            - "tags.*.name"
          value_field: "tags.*.slug"
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "content/events"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" } # Required for display in CMS
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - label: "Location"
        name: "location"
        widget: "relation"
        collection: "meta"
        file: "locations"
        search_fields:
          - "locations.*.name"
        display_fields:
          - "locations.*.name"
        value_field: "locations.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          search_fields:
            - "tags.*.name"
          display_fields:
            - "tags.*.name"
          value_field: "tags.*.slug"
      - { label: "Body", name: "body", widget: "markdown" }
